[package]
name = "fuzz"
version = "0.1.0"
authors = ["JIexa <malyshevalexey8@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
regex = "*"
env_logger = "*"
log = "*"
